spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

BASE_URL: "http://ec2-34-201-216-252.compute-1.amazonaws.com/"